### ISSUE TITLE
ActionMenu - Reposition tied to FPS

### ISSUE THREAD

**Issue by NotAKidoS** [dakyneko/DakyModsCVR#14]
hard to position menu with any sort of precision unless you have low fps

**Comment by dakyneko** [comment]
In fact the input widget speed is tied to cohtml input update rate, thus it's a more global issue. A fix could be to have a timer in js and move according to a delta time to be fps-independent. 🤔 

See https://github.com/dakyneko/DakyModsCVR/commit/a0d670e7a8ce186153140915853d6ead810b875b

thoughts? idk how to test different fps
