### ISSUE TITLE
ActionMenu - Repositioning menu after avatar change causes menu offset to reset

### ISSUE THREAD

**Issue by NotAKidoS** [dakyneko/DakyModsCVR#19]
repositioning menu, then switching avatar, then repositioning menu again causes menu offset to reset

slight annoyance

**Comment by dakyneko** [comment]
Yeah it's because we don't rebuild the submenu with `BuildMelonPrefsMenus` thus the values are as they were at startup. The bug should happens also if reload with F3. If we go with more dynamic generation of this menu and melon prefs due to #18 maybe this will be solved too.

**Comment by dakyneko** [comment]
Is this still relevant and happening? feel free to reopen if yes
