### ISSUE TITLE
ActionMenu - Add dedicated keybind to open menu

### ISSUE THREAD

**Issue by ShaunDreclin** [dakyneko/DakyModsCVR#21]
Ideally rebindable through the SteamVR bindings menu but if that's not possible just any way to set the button.

For desktop users it should probably default to R (if that binding isn't already used by anything) to be consistent with VRC

**Comment by dakyneko** [comment]
addressed in https://github.com/dakyneko/DakyModsCVR/commit/e974cde59b9f09103201d332a30cb68f8e70e1de for next release
