### ISSUE TITLE
ActionMenu - Deep submenus dont have a back button unless eccentric back is off

### ISSUE THREAD

**Issue by Patchuuri** [dakyneko/DakyModsCVR#31]
Going several submenus deep into the menu with the freezeframe/camera animations mod will not show the back button unless eccentric back is disabled

with eccentric back enabled:
![image](https://user-images.githubusercontent.com/108003868/194713924-e59927dd-2c8d-4eba-bdaf-9792c793b1ca.png)
![image](https://user-images.githubusercontent.com/108003868/194713931-240f21ef-7d83-414e-a832-e015ddb4fe7e.png)
![image](https://user-images.githubusercontent.com/108003868/194713935-0728c999-2f91-473b-9ba4-de91bf9ed384.png)
![image](https://user-images.githubusercontent.com/108003868/194713942-5481933a-7893-4a00-b1df-99b5f7815392.png)

with eccentric back disabled:
![image](https://user-images.githubusercontent.com/108003868/194713975-81f1989a-eb7b-436c-a124-e9f2109f2d3f.png)

MelonPrefs:
[ActionMenu]
flick_selection = false
quickmenu_long_press = false
boring_back_button = false
dont_install_resources = false
split_overcrowded_avatar_menu = true
menu_size = 0.5
menu_position_offset = [ 0.468075811862946, 0.421068012714386, ]

**Comment by dakyneko** [comment]
this is fixed in last version. thanks for reporting
