### ISSUE TITLE
LagFreeScreenshots - Ignores selected Portable Camera filter.

### ISSUE THREAD

**Issue by NotAKidoS** [dakyneko/DakyModsCVR#35]
The saved image will not have the selected portable camera filter applied.

Expected:
![image](https://user-images.githubusercontent.com/37721153/214417306-e211ad52-f572-4b2e-b495-369799ce62fd.png)
Result:
![ChilloutVR-2023-01-24_15-13-07 488](https://user-images.githubusercontent.com/37721153/214417359-f18d064b-d248-4ffd-99b9-65181add44cb.png)

**Comment by dakyneko** [comment]
fixed by 6cf659883d9f26948e7cb665961331041b6dd3af and it's cursed, your welcome
