### ISSUE TITLE
LagFreeScreenshots - Format setting should be an Enum of supported formats.

### ISSUE THREAD

**Issue by NotAKidoS** [dakyneko/DakyModsCVR#38]
The format setting should be an enum of supported formats, not a string.

![image](https://user-images.githubusercontent.com/37721153/214422975-43fb84ea-2ded-44d6-a66e-29bd40fc9326.png)

**Comment by dakyneko** [comment]
fixed 48eecd1bccd1a5b2ea844d899d59cf1186ec9912
