### ISSUE TITLE
LagFreeScreenshots - Webp support libs should use standard UserLibs folder.

### ISSUE THREAD

**Issue by NotAKidoS** [dakyneko/DakyModsCVR#39]
The library used for webp support should not be required to be placed in the main ChilloutVR directory. 

MelonLoader creates a UserLibs folder for this exact purpose:
![image](https://user-images.githubusercontent.com/37721153/214425841-ce2c8c3b-2ebd-4ebb-a7bf-b85a84d90424.png)

**Comment by dakyneko** [comment]
ML has a bug with it. Won't fix for now.
