### ISSUE TITLE
ActionMenu - Preformance Chug when opened

### ISSUE THREAD

**Issue by Dal1ster** [dakyneko/DakyModsCVR#41]
When opening the action menu, the game seems to slow down and lag by from what i know half. this doesn't happen when the menu is closed, only when the menu is open.

**Comment by dakyneko** [comment]
Hello. Cohtml and cvr 2023 is known to have perf issue. I didn't had time to check in VR but try the new version (see changelog) https://github.com/dakyneko/DakyModsCVR/releases/tag/preview21 It helps?

**Comment by axel-angel** [comment]
@Dal1ster ping. Gonna mark as solved if no reply, I couldn't reproduce after the fix

**Comment by dakyneko** [comment]
@Dal1ster ping. Will mark as solved if no reply, I couldn't reproduce after the fix

**Comment by dakyneko** [comment]
new CVR removed the FPS limit because they solved the performance issue, hopefully this also fix for action menu. feel free to reopen if you see problems.
